# Generated by Django 5.2.5 on 2025-08-15 04:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorymovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9-]{3,64}$', 'SKU inválido (usa A-Z, 0-9 y guiones).')]),
        ),
    ]
